networks:
  nyc-traffic-net:
    driver: bridge

services:

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 5400000
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
    networks:
      - nyc-traffic-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1g

  spark-master:
    build:
      context: ./spark
      dockerfile: spark-master.Dockerfile
    container_name: spark-master
    restart: unless-stopped
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_HOME: /opt/spark
    env_file: .env
    command: /opt/spark/sbin/start-master.sh
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - nyc-traffic-net

  spark-slave:
    build:
      context: ./spark
      dockerfile: spark-slave.Dockerfile
    container_name: spark-slave
    restart: unless-stopped
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_HOME: /opt/spark
    env_file: .env
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - nyc-traffic-net

  job-a:
    build: ./job-a
    container_name: job-a
    restart: unless-stopped
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - nyc-traffic-net

  job-b:
    build: ./job-b
    container_name: job-b
    restart: unless-stopped
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      spark-master:
        condition: service_started
    networks:
      - nyc-traffic-net